import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import TheHeader from "@/components/layout/header/TheHeader";
import TheFooter from "@/components/layout/footer/TheFooter";

const nunito = Nunito({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        {/* <TheHeader /> */}
        <main className=" pt-[50px] pb-[50px]">{children}</main>
        {/* <TheFooter /> */}
      </body>
    </html>
  );
}
